// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type Image struct {
	ImageID   string
	Filename  string
	Format    string
	CreatedAt int64
}

type Note struct {
	NoteID    string
	Body      string
	CreatedAt int64
}

type Session struct {
	SessionID string
	CreatedAt int64
}

type WebauthnCredential struct {
	CredentialData *JSONCredential
	CreatedAt      int64
}

type WebauthnSession struct {
	WebauthnSessionID string
	SessionData       *JSONSessionData
	CreatedAt         int64
}
