// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Challenge struct {
	ChallengeID string
	Bytes       []byte
	CreatedAt   time.Time
}

type Image struct {
	ImageID   string
	Filename  string
	Format    string
	CreatedAt time.Time
}

type Note struct {
	NoteID    string
	Body      string
	CreatedAt time.Time
}

type Passkey struct {
	PasskeyID     []byte
	PublicKeySpki []byte
	CreatedAt     time.Time
}

type Session struct {
	SessionID string
	CreatedAt time.Time
}
