#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# go install github.com/air-verse/air@latest

air --build.cmd "go build -o ./bin/yellhole" --build.bin "./bin/yellhole" -build.include_ext="go,gohtml,js,css" --build.exclude_dir "data"