name: govulncheck
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Security Check
        id: govulncheck
        uses: golang/govulncheck-action@v1